[build]
  command = "npm install"
  publish = "."

[functions]
  # Only process files in the netlify/functions directory as serverless functions
  directory = "netlify/functions"
  node_bundler = "esbuild"
  timeout = 25
  # Explicitly ignore all other directories
  included_files = ["netlify/functions/**"]

[build.environment]
  NODE_VERSION = "18.0.0"

# APIリクエストをバックエンド関数にプロキシする
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# その他のリクエストはフロントエンドに流す
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  targetPort = 3000
  command = "npm run dev"
  port = 8888
  publish = "."
